### PR TITLE
Don't emit empty statement in ClassTransformer if initInstanceVariables is empty

### LINKED ISSUE #1822: static member variable causes Unexpected token ;
the following code causes a ```Unexpected token ;``` error when running the code
```js
// Options: --member-variables
class Test {
 static myVar = 0; 
}
```
translates to
```js
$traceurRuntime.ModuleStore.getAnonymousModule(function() {
  "use strict";
  var Test = function Test() {
    ; // ERROR HERE
  };
  ($traceurRuntime.createClass)(Test, {}, {myVar: 0});
  return {};
});
```

The error is on line 4, [REPL here](https://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--member-variables%0Aclass%20Test%20%7B%0A%20static%20myVar%20%3D%200%3B%20%0A%7D)

### PR DESCRIPTION
**Pull request by caitp**
Closes #1822

### CODE REVIEW

**Comment by caitp** [comment]
the behaviour looks good to me for es5 and es6 script-mode with/without extends clause and with/without default constructors. will add tests..

**Comment by caitp** [comment]
@johnjbarton I think erik is gone for the week, but do you have an opinion on this? It's a pretty minor change and it sounds like at least one engine (I would bet JSC, although Safari on ios 8.2 didn't seem to have a problem with it) didn't like the empty statement

**Comment by johnjbarton** [comment]
@caitp can you help me understand how `initInstanceVars` gets a value? I only see its initialization to `[]`.

While I appreciate your test cases, we generally try to avoid using generated code as test expectations. (I regret the cases where we accepted them in the past).  The generated code can vary a great deal without altering the validity of the transformation.  By testing the operational result of the transformation on the evaluated program, the test becomes sensitive to only the transformation.  For example, by verifying that an instance of a class is initialized with the values in the class body we check the transformer without the test failing if we change formatting and so on.  That is why almost all of our *Transformer tests are actually 'feature' tests.

**Comment by caitp** [comment]
@johnjbarton it gets aliased as `initVars` while being modified (`initVars` points to either the static vars array or the instance vars array depending on the presence of the `static` keyword)

**Comment by caitp** [comment]
getting rid of the tests is fine --- the code "works" one way or the other, the empty statement being a syntax error was apparently a bug in the original report

**Comment by johnjbarton** [comment]
Of course you would have exactly the example where feature tests don't work!  

What do you think about adding a check in `ConstructorValidator` that we are not emitting empty statements?  I'd like to have some way to know that this is moving forward and that we don't break it later.

**Comment by caitp** [comment]
@johnjbarton I'm not sure there's a good way to do that (would need to know if the constructor is a default constructor or not) --- how about a codegen test which just verifies that there aren't 2 semicolons after "use strict", with whitespace/line endings removed?

**Comment by johnjbarton** [comment]
Yes, but I think you can just check the transformed tree and only for the cases that would fail if this PR were not in place.

**Comment by caitp** [comment]
added a simpler test case which makes assertions about the structure of the transformed AST itself... tried to be as indirect as possible so that it doesn't break often.

**Comment by arv** [comment]
An even simpler test would be to transform the tree, write it and compare it with the expected output. We have a few tests like that where we want to make sure the generated code "looks good".

**Comment by caitp** [comment]
Yeah, @johnjbarton wasn't keen on that

**Comment by johnjbarton** [comment]
That's what the original PR did.  See https://github.com/caitp/traceur-compiler/commit/8d9df81fcc741825df6b593d33be0c8cff86f864 and my comments above.

If the Find apparatus was as part of our system rather than in this test it would look a lot better.

**Comment by johnjbarton** [comment]
Also, the parsing should be done with Compiler.parse.

**Comment by arv** [comment]
@johnjbarton That commit has no test.

When testing that the constructor does not contain an empty expression I think it is cleaner to just look at the generated code instead of inspecting the AST.

@caitp Sorry for the conflicting input.

**Comment by caitp** [comment]
@arv there was a test suite (basically the ES6ClassTransformer tests adapted for ClassTransformer), but he wasn't keen on testing the generated code, preferring the functional testing. However, since functionally the empty statement is fine, it can't really be verified that way. The test was removed when the commit was amended

Honestly, there isn't much point in the patch, it just makes the output a bit cleaner. the original bug report mentioned a syntax error, but that seems to have been a mistake on the part of the poster.

**Comment by arv** [comment]
I totally support the functional changes of this. I'm also fine just skipping a test for it. What I don't like is the current test since it is too complicated for what it needs to test.

**Comment by caitp** [comment]
Removed the test case

**Comment by arv** [comment]
LGTM

**Pull request merged**
