### PR TITLE
Publish npm version 0.0.81

### PR DESCRIPTION
**Pull request by johnjbarton**
TBR=@arv

### CODE REVIEW

**Comment by arv** [comment]
Thanks.

(I tried this morning but I kept getting npm server errors. I think my machine has some issue with npm publish.)

**Comment by johnjbarton** [comment]
I think npm publish has some issues. It took me two times, a record low.  I'll try to look into this before our next release.

**Comment by arv** [comment]
I saw @domenic mentioning that this might be an issue with corporate firewalls ;-)

**Comment by jmm** [comment]
@johnjbarton Is there supposed to be an [`0.0.81` tag](https://github.com/google/traceur-compiler/tree/0.0.81)?

**Comment by johnjbarton** [comment]
Our automatic publish script, `make git-update-publish` creates the tags. For 0.0.81 the script failed. It worked for 0.0.82.

**Pull request closed without merging**
