### PR TITLE
bin/BrowserSystem.js includes compiler, polyfills, System, and WebPag…

### PR DESCRIPTION
**Pull request by johnjbarton**
Now includes compiler, polyfills, System, and WebPageTranscoder.

Read traceurOptions attribute from <script type=module traceurOptions="--asyncFunctions">.
Use bin/BrowserSystem.js + System.import in repl.html to demo dynamic import.
Use bin/BrowserSystem.js + System.loadScriptTypeModule() in async.html/await.html to
  demo script tag import.

### CODE REVIEW

**Comment by johnjbarton** [comment]
This add two large files to our npm module (BrowserSystem.js and traceur.js.map), but it greatly simplifies the instructions for browser.  I think we could load the compiler dynamically into BrowserSystem, but I don't know that this complication is worthwhile to save 1MB.

**Comment by arv** [comment]
LGTM

I'm not sure what's up with the cla bot?

Also, can you provide a good commit message. The current one is not as good as your comment.

**Comment by johnjbarton** [comment]
I think the github UI was "improved".  The PR description is now spread over three parts, the PR title, the PR description, and the first commit.  Combined it has the same content as the commit. I'm sure someone thinks it makes sense.

I'll look into the CLA snafu, I guess its because my legacy email address confuses it.

**Comment by arv** [comment]
FWIW, I gave up on pulley. Now that github can squash the commits we are
better off just cleaning up the commit message using the web ui.

**Pull request closed without merging**
