### PR TITLE
Refactor member variable transformer

### PR DESCRIPTION
**Pull request by arv**
This removes the member variable transformer logic from the class
transformer in favor of reusing the old ES6ClassTransformer.

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

The diff looks a lot larger because of the file renames. I can rename it back the old file names for the sake of the review if you prefer?

@vicb FYI

**Comment by johnjbarton** [comment]
What would help the most is more/different commit description. For example, "reusing the old ES6ClassTransformer" seems to conflict with that file being deleted.

**Comment by arv** [comment]
PTAL

I split it into 2 commits. The second one is pure rename and can mostly be ignored when reviewing.

I changed the commit message slightly:

```
Refactor member variable transformer
    
This removes the member variable transformer logic from
ClassTransformer. Instead we use the alrady existing
ES6ClassTransformer which does this as a stand alone transformer.
```

**Comment by johnjbarton** [comment]
LGTM but the change to the test case seems suspicious.

**Pull request merged**
