### PR TITLE
Feature test runner: Flip the policy regarding script/module

### PR DESCRIPTION
**Pull request by arv**
The feature test runner now treats `.js` as Module and `.script.js`
as Script.

Rename files as needed. Some tests need global context and some needs
sloppy mode.

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

Motivation. For #1979 I want to use mocha's `--compilers` flag and for that I only want to test modules (since node only supports commonjs modules, never global scope).

**Comment by johnjbarton** [comment]
Some of these are Add/Delete instead of rename. Was that intended?

**Comment by arv** [comment]
That's just git thinking too much changed to be considered a move. They were all moves before I had to change the error message for example.

**Comment by johnjbarton** [comment]
LGTM

**Pull request merged**
