### PR TITLE
Cleanup parser enums and optional params

### PR DESCRIPTION
**Pull request by arv**
This gives another ~10% performance improvement.

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

**Comment by johnjbarton** [comment]
Nice LGTM

**Comment by arv** [comment]
To be fair it seems like the perf improvements are pretty high for this change.

Things that make it faster:

- No optional params means no arguments adaptor due to passing wrong number of arguments
- No `arguments` object needed any more
- More likely to be monomorphic due to always passing the right type.

**Comment by johnjbarton** [comment]
and some of the functions involved are called many times I guess.

**Pull request merged**
