### PR TITLE
Generated code dependencies aren't running

### PR DESCRIPTION
**Pull request by guybedford**
These tests pass, when the added test should clearly fail.

### CODE REVIEW

**Comment by guybedford** [comment]
Huh, amazing! Ok the tests do work, it's just my machine that for some reason isn't running them.

**Comment by arv** [comment]
I ran into a similar issue here: https://github.com/google/traceur-compiler/commit/f52129113bc7e19b601ae6fb406fa1cb03fd2592#diff-f74b09a4e643e4fcbf764349c4faeed9R485

These async tests are not handling failures correctly.

**Comment by johnjbarton** [comment]
Any idea what changed? For sure these tests run and fail commonly in the past.

**Comment by guybedford** [comment]
@johnjbarton I realised I had a syntax error in the test file itself, which instead of failing just doesn't run those tests.

**Pull request closed without merging**
