### PR TITLE
Use build/versionInfo.js for npm just-publish

### PR DESCRIPTION
**Pull request by johnjbarton**
And bump the version beyond the one published to npm.

### CODE REVIEW

**Comment by arv** [comment]
What about this?

https://github.com/google/traceur-compiler/blob/master/build/incrementSemver.js#L20-L21

**Comment by johnjbarton** [comment]
removed it.

**Comment by arv** [comment]
LGTM

Thanks for resolving this so fast. I'll look at making the dist/commonjs from the npm build next. Once that is done we should remove the part of the makefile that handles npm publish.

**Comment by johnjbarton** [comment]
I didn't want to remove the makefile bit until we see that the npm version is better.  So far, not a win ;-)  Let me see how it works now.

**Pull request closed without merging**
