### PR TITLE
Fix incorrect URL

### PR DESCRIPTION
**Pull request by kaleb**

### CODE REVIEW

**Comment by UltCombo** [comment]
This probably explains why the Wiki `GettingStarted` page keeps getting re-created by random people. Nice work!

**Comment by arv** [comment]
Thanks.

I see that you have signed the CLA. However, we need to add an entry to AUTHORS as well. Since the AUTHORS file is on master we will need to do two PR. Sorry about that.

I can also just make the change to index.html if you do not are about getting the commit?

**Comment by johnjbarton** [comment]
The patch needs to be applied to master then pushed to gh-pages when we
publish.

**Comment by arv** [comment]
True. I thought that we only had index.html on the gh-pages branch.

**Comment by kaleb** [comment]
I don't need to be added to AUTHORS.

**Comment by johnjbarton** [comment]
Thanks the fix is in the repo and will be pushed on the next publish.  See #1679

**Pull request closed without merging**
