### PR TITLE
Use docker based travis CI

### PR DESCRIPTION
**Pull request by johnjbarton**
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

### CODE REVIEW

**Comment by arv** [comment]
LGTM. The change to the Travis file is a bit cryptic but I read the docs and that is how it is done.

**Comment by domenic** [comment]
This is actually unnecessary: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

> The default behavior when no sudo usage is detected is to send Linux builds to this infrastructure.

**Comment by johnjbarton** [comment]
Well it looks like Travis is non-responsive which is why I was bothering at all.

**Comment by arv** [comment]
https://travis-ci.org/google/traceur-compiler reads

> This job ran on our legacy infrastructure. Please read our docs on how to upgrade

which links to http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

and it says to add `sudo: false`.

so, we should probably just merge this.

**Comment by domenic** [comment]
Fascinating, and good to know for my own projects. Thanks for finding that.

**Pull request closed without merging**
