### PR TITLE
fixes windows paths in node tests

### PR DESCRIPTION
**Pull request by pflannery**
fixes source map relative path test for windows

### CODE REVIEW

**Comment by domenic** [comment]
This seems to depend on Traceur being installed globally?

**Comment by arv** [comment]
What @domenic said. We want the test to test the current version of traceur and not the installed one.

I believe the solution is to use `node ../../traceur` but I ran into some issues with that.

**Comment by pflannery** [comment]
> This seems to depend on Traceur being installed globally?
@domenic your right it was, I realised that just after I went out. I've fixed now.

@arv I've got it to work with the original paths. it seemed like this was the only [failing point](https://github.com/pflannery/traceur-compiler/blob/1a4f752430d2d2282486da7470316ba2a0ffcb31/test/unit/node/generated-code-dependencies.js#L303) but the '\' replace solves that too.

Sorry that I had to bring this back up but it's got in the way of the other PR where I'm trying to solve another route other than use options for the `rootModules` property...

**Comment by arv** [comment]
LGTM

**Pull request merged**
