### PR TITLE
Rename 'instantiate' format to 'system' format

### PR DESCRIPTION
**Pull request by guybedford**
This will make the naming of this format the same between Traceur, Babel and TypeScript.

In due course though I do plan to change the name, but this will go along with separating the format from the `System` loader to make the output look like:

```javascript
Reflect.loader.register(...);
```

When we do this, we can come up with a new output name, perhaps something like `register` or `loader` format.

It will be a little while still on the above though.

Let me know if you have any reservations at all about these ideas too.

### CODE REVIEW

**Comment by arv** [comment]
LGTM

@johnjbarton Can you look at this since I want your buy in as well.

**Comment by johnjbarton** [comment]
Sorry, I'm not especially enthusiastic. I don't understand why "system" is a better option name than "instantitate".  There is no indication that whatwg plans to define a "System" global, so this option name is deprecated out of the gate. If the goal is to generate `Reflect.loader.register' calls it's even more confusing as the format would not even invoke methods of `System`. Moreover this name on the files is confusing. 

'systemjs' would make sense if we meant "The format used by systemjs". 'register', 'whatwg', 'es6' are all good if we believe that this format is especially blessed. 'getter' or 'encapsulated' or some word that evokes the format would also be good.

That all said, not the end of the world if you want go with 'system'.

**Comment by guybedford** [comment]
@johnjbarton thanks for the feedback - yes the format is effectively already deprecated, although the timescales are on our side here.

The path out of deprecation is to make the change to a `Reflect.loader.register` along with another name change of the format when the time comes.

This is more about having consistency across projects for users. Having the same format meaning the same thing will make it easier for users to use the format and switch between projects, say if they are wanting to switch to Traceur for performance gains in builds.

I can equally accept if you don't want to make the change, it's just a suggestion for consistency.

**Comment by johnjbarton** [comment]
Changing the format twice seems worse for users unless the time scale is very long.

**Comment by guybedford** [comment]
Sure, that's a good point. If you'd rather just make the one change perhaps towards the end of this year, then I'm happy to stick with that.

I would still like to call it `register`, if this name becomes available by then. Otherwise have more than enough time to think of something else!

**Comment by MajorBreakfast** [comment]
Why can't it be called register now?

**Comment by guybedford** [comment]
Thanks for the feedback here. Closing for now - lets come back to this then when we can convert the output to `Reflect.loader.register`.

**Comment by johnjbarton** [comment]
#1919 frees the name 'register'.  Does anything else block you from our side?

**Comment by guybedford** [comment]
@johnjbarton thanks so much for that! Just holding back here for now to minimize the further user-facing changes as you mentioned to rather do the switches all at once across the transpilers later in the year. (renaming to `register` and setting to `Reflect.loader.register`). Suggestions welcome though.

**Pull request closed without merging**
