### PR TITLE
Fix RegExp test expectation

### PR DESCRIPTION
**Pull request by arv**

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton TBR

@mathiasbynens I assume something changed in regexpu? Travis is using v0.3.0:
https://travis-ci.org/google/traceur-compiler/builds/48171570

**Comment by johnjbarton** [comment]
This test fails for me

**Comment by arv** [comment]
Remove your node_modules and make clean and it should pick up a more specific version of regexpu.

Two other options:

1. Hard code the version in our package.json
2. Change test to be more resilient.

**Comment by johnjbarton** [comment]
Seems like we should set the version, otherwise we don't have a certain environment.

**Comment by arv** [comment]
Hmm... we already set the version.

**Comment by johnjbarton** [comment]
We are set to 0.3 but the change here seems to require 1.1.

**Comment by mathiasbynens** [comment]
FWIW, the change fixes [an issue reported by Marja](https://github.com/mathiasbynens/regexpu/issues/16); hence the new output. The fix is part of regexpu v1.1.0 indeed.

**Pull request merged**
