### PR TITLE
Correct check for undefined variable

### PR DESCRIPTION
**Pull request by mathiasrw**
The code was comparing the result of `typeof` with a variable named `undefined`.

As typeof returns a string it should compare to `'undefined'`

### CODE REVIEW

**Comment by arv** [comment]
Thank you.

I'll merge once the tests pass.

**Comment by arv** [comment]
@mathiasrw Can you also add an entry to AUTHORS?

**Comment by mathiasrw** [comment]
Sure :)

**Comment by arv** [comment]
Thanks.

This is consistently failing on `node v6.5.0 (npm v3.10.3)`. Not sure why that is?

**Comment by mathiasrw** [comment]
Interesting. 

I will look into if node 6.5 have any special things regarding `typeof`

**Comment by mathiasrw** [comment]
@arv 

When testing the master branch - without my changed code - it works on node 6.4 but not on 6.5: https://travis-ci.org/mathiasrw/traceur-compiler/builds/159081592

Node 6.5 was released the 8th of September: https://nodejs.org/en/download/releases/

I see that last test run was 9th of June: https://travis-ci.org/google/traceur-compiler/builds

So, the test fails because of a new Node release...

I will try to dig a bit down into why and come back with inputs if I find anything...

**Comment by arv** [comment]
That's unlucky. I'll look too.

**Comment by arv** [comment]
I fixed the test. Merging.

Thanks again.

**Comment by mathiasrw** [comment]
Perfect - thanks for quick action :)

**Pull request merged**
