### PR TITLE
Update build version and add fix for file manipulation issue

### PR DESCRIPTION
**Pull request by HitendraSinghRathore**
https://github.com/google/traceur-compiler/issues/2144
Fix for the above mentioned issue
Removed the mkdirRecursive call.

### CODE REVIEW

**Comment by HitendraSinghRathore** [comment]
@arv can you please review the PR.

**Comment by arv** [comment]
This seems OK to me but I'm not comfortable to approve this package-lock.json. I know the node ecosystem now uses this and I think that is fine but I cannot review a 1500 lines of config file that has been used in the past to inject malicious dependencies.

If you remove the package-lock.json I can merge this for you.

**Comment by HitendraSinghRathore** [comment]
Makes sense, Removed the package-lock file. @arv

**Comment by arv** [comment]
Thanks

**Pull request merged**
