### PR TITLE
Make compatible with TypeScript compiler (by adding ".js" postfix if it was missing)

### PR DESCRIPTION
**Pull request by iislucas**
If a module fails to load, and the module name does not end in ".js", and adding ".js" postfix will make the file load, then do that. This makes traceur compatible with TypeScript, which current emits import statements that don't include the ".js" postfix. 

See: 
https://github.com/google/traceur-compiler/issues/1997
and 
https://github.com/Microsoft/TypeScript/issues/5460

Added test, and testes with `make test`

[Review on Reviewable](https://reviewable.io/reviews/google/traceur-compiler/1999)

### CODE REVIEW

**Comment by arv** [comment]
I think this needs to be guarded by an option. We don't want to go back to allowing this by default.


---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[src/runtime/TraceurLoader.js, line 155 \[r1\]](https://reviewable.io:443/reviews/google/traceur-compiler/1999#-K1tGKhS9IneJtgzC7QM)** ([raw file](https://github.com/google/traceur-compiler/blob/791cbf1f448daecea8438cd6c1275e7020245f24/src/runtime/TraceurLoader.js#L155)):</sup>
Missing `{}`


---

<sup>**[test/unit/runtime/Loader.js, line 150 \[r1\]](https://reviewable.io:443/reviews/google/traceur-compiler/1999#-K1tGaZUPi1b5HTr89et)** ([raw file](https://github.com/google/traceur-compiler/blob/791cbf1f448daecea8438cd6c1275e7020245f24/test/unit/runtime/Loader.js#L150)):</sup>
You can use ES6 here so a template literal would have been cleaner.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/traceur-compiler/1999)

**Comment by iislucas** [comment]
Just closing the loop on this. I ended up finding another way to do this, so I don't mind leaving this as is. If someone else needs traceur, then can easily finish this up. :)

**Comment by arv** [comment]
OOC did TypeScript finally change this?

**Comment by iislucas** [comment]
I don't think so; I just found an easier way using the closure compiler, which solves another problem I was having also (actually doing the module loading).

**Pull request closed without merging**
