### PR TITLE
Correct backslashes after resolve() in tval

### LINKED ISSUE #1831: Tests are failing on Windows

### PR DESCRIPTION
**Pull request by johnjbarton**
Fixes #1831

### CODE REVIEW

**Comment by johnjbarton** [comment]
Tested on Linux, so I'm just guessing this will solve Windows.

**Comment by pflannery** [comment]
> Tested on Linux, so I'm just guessing this will solve Windows.

I just tried this and a new error for windows is now being spat out:
```
Test setup FAILED  Error: Error: ENOENT: no such file or directory, open 'd:\unit\unitTestRunner.js'
Specified as ../../unit/unitTestRunner.js.
Imported by d:\dev\github\pflannery\traceur-compiler\test\unit\util\getopt.js.
Normalizes to d:../../unit/unitTestRunner.js
locate resolved against base 'd:/dev/github/pflannery/traceur-compiler/'
```

**Comment by johnjbarton** [comment]
> Normalizes to d:../../unit/unitTestRunner.js
Probably the normalize code is expecting `/` all the way.

**Comment by pflannery** [comment]
> Probably the normalize code is expecting / all the way.

It looks to me that either the `refererName` never gets normalized or its something to do with splitting the `refererName` during the `runtime\url.js`

this is whats called [here](https://github.com/google/traceur-compiler/blob/master/src/runtime/ModuleStore.js#L213) 
```return resolveUrl("D:\dev\github\pflannery\traceur-compiler\test\runUnitTests.js", "./unit/unitTestRunner.js")```

then the [split(base) code returns](https://github.com/google/traceur-compiler/blob/master/src/runtime/url.js#L285)

```js
["D:\dev\github\pflannery\traceur-compiler\test\runUnitTests.js", 
"D", 
undefined, 
undefined, 
undefined, 
"\dev\github\pflannery\traceur-compiler\test\runUnitTests.js", 
undefined, 
undefined]
```
[finally resolveUrl returns](https://github.com/google/traceur-compiler/blob/master/src/runtime/url.js#L307) "D:unit/unitTestRunner.js"

**Comment by pflannery** [comment]
ignore last comments. @johnjbarton your right we need to replace '\' each time were loading from a new module just like you have here.

**Comment by pflannery** [comment]
found the bugger - changing [this](https://github.com/google/traceur-compiler/blob/master/src/runtime/url.js#L285) to ```var baseParts = split(base.replace(/\\/g, '/'));``` lets me run the tests on windows :)

**Comment by johnjbarton** [comment]
Thanks! We need to trace back to where base comes in and apply the `replace()` there. Let me look.

**Comment by johnjbarton** [comment]
I can't find where the backslash path is sneaking through. The promises jungle makes debugging this difficult.

I think we should land this much, in hopes that we'll get some insight on the remaining problem.

**Comment by arv** [comment]
I can take a look tonight since I have Windows at home.

**Comment by pflannery** [comment]
if it helps I've traced it back to [here](https://github.com/google/traceur-compiler/blob/master/src/runtime/InternalLoader.js#L258) and doing this instead
```js
this.getOrCreateCodeUnit_(name.replace(/\\/g, '/'), referrerName.replace(/\\/g, '/'), address, metadata);
```  
gets the tests running.

The command I'm using is this ```iojs tval ./test/runUnitTests.js``` and to make it simpler to recreate the issue I comment out the following [here](https://github.com/google/traceur-compiler/blob/master/test/unit/unitTestRunner.js#L17-L29) and just use `ErrorReporter.js` as its a failing point
```js
  patterns: [
    'test/unit/util/ErrorReporter.js',
    //'test/unit/syntax/*.js',
    //'test/unit/codegeneration/*.js',
    //'test/unit/semantics/*.js',
    //'test/unit/tools/*.js',
    //'test/unit/runtime/*.js',
    //'test/unit/system/*.js',
    //'test/unit/node/*.js',
    //'test/unit/*.js'
  ]
```

**Comment by arv** [comment]
I'm making some progress.

1. make sure there are no `.generated.js` files remaining. This set me up more than once.
2. https://github.com/google/traceur-compiler/blob/master/test/modular/Mocha6.js#L46

But the main issue is that `traceur` "is not recognized as an internal or external command, operable program or batch file."

**Comment by arv** [comment]
https://github.com/google/traceur-compiler/pull/1857

**Comment by johnjbarton** [comment]
obsolete

**Pull request closed without merging**
