### PR TITLE
Split src/traceur.js into compiler, loader, and util imports.

### PR DESCRIPTION
**Pull request by johnjbarton**
This is a first step to separate out the Loader from the Compiler as well as removing test-only code from the compiler.

### CODE REVIEW

**Comment by arv** [comment]
Looks like you forgot to git add files?

**Comment by johnjbarton** [comment]
sorry, PTAL

**Comment by arv** [comment]
LGTM

I assume the code hasn't changed, just moved?

Can you set the right copyright year in the new files?

**Comment by johnjbarton** [comment]
Just moved. Updated the dates.

**Pull request closed without merging**
