### PR TITLE
Upgrade semver to 4.3.3

### PR DESCRIPTION
**Pull request by johnjbarton**
TBR=arv@

### CODE REVIEW

**Comment by UltCombo** [comment]
Kinda odd to not use a semver range to depend on semver. :sweat_smile:

**Comment by arv** [comment]
haha

@johnjbarton What was the motivation for this change?

**Comment by johnjbarton** [comment]
I guess you are suggesting 4.3.x? Or?

I'm trying to update to minimize changes in another system.

**Comment by UltCombo** [comment]
I would suggest `^4.3.3` (that means "compatible with 4.3.3", which is equivalent to `>= 4.3.3 < 5`), or `~4.3.3` (equivalent to `>= 4.3.3 < 4.4.0`) if you don't want to pull in minor version releases (that is, versions that include new features in a backwards-compatible way) automatically.

Accepting minor versions is usually a good idea as these tend to also include bug fixes, but some paranoid people fear that these may have a bigger chance of containing accidental backwards-incompatible breaking changes (which I hope wouldn't happen to the semver package itself! :smile:).

**Pull request closed without merging**
