### PR TITLE
Fix test on Windows

### PR DESCRIPTION
**Pull request by arv**
There were/are 2 issues

1. Backslashes in paths (sigh)
2. child process exec has probelm with executing unix style
executables on Windows. Skip tests on Windows :'(

### CODE REVIEW

**Comment by domenic** [comment]
IIRC execFile works fine even though exec doesn't. Or maybe it was spawn...

**Comment by arv** [comment]
Let me try that

**Comment by UltCombo** [comment]
Or you can just prepend the command with `node` and remove the shebang, that's how npm hacks around that issue.

**Comment by arv** [comment]
Prefixing with `node`: I tried that. the node module gets executed with the wrong cwd or something.

**Comment by arv** [comment]
`execFile` does not help for me. I'll have to look at this more later since my time slot for Windows is running short.

**Comment by johnjbarton** [comment]
LGTM

**Comment by pflannery** [comment]
LGTM, tests for this PR are passing on my windows 8.1 64bit (iojs 1.6.3)

windows cmd output
```cmd
D:\temp\traceur-compiler>node tval ./test/runUnitTests.js

  ...........................................................
  ............................................................
  ............................................................
  ............................................................
  ............................................................
  ............................................................
  ............................................................
  ............................................................
  ............

  491 passing (8s)
```

windows git bash output
```sh
$ tval ./test/runUnitTests.js

  ...............................................................................................................
  ................................................................................................................
  ................................................................................................................
  ................................................................................................................
  ............................................

  491 passing (8s)
```

**Pull request merged**
