### PR TITLE
Travis CI: Test on Node.js v4.x.x and v5.x.x

### PR DESCRIPTION
**Pull request by SrinivasanTarget**

### CODE REVIEW

**Comment by arv** [comment]
What is the motivation of this? I can see a few reasons but I would like to know yours?

The downside of doing this is that it takes longer before we know the results...

**Comment by SrinivasanTarget** [comment]
@arv  I don't think it will take sometime to know the results as CI took very less time to update the results back. Also i feel it would be always great to test features not only on latest stable version and also the stable versions that are widely used. Please let me know your thoughts.

**Comment by SrinivasanTarget** [comment]
@arv ping

**Comment by arv** [comment]
LGTM

@SrinivasanTarget Did you sign the CLA? Can you add yourself to AUTHORS?

@johnjbarton Can you check the clasigners (I can no longer access it)?

**Comment by SrinivasanTarget** [comment]
Please let me know how to sign CLA?

**Comment by arv** [comment]
Instructions are here: https://github.com/google/traceur-compiler/blob/master/CONTRIBUTING.md

**Comment by SrinivasanTarget** [comment]
I have signed the CLA.

**Comment by SrinivasanTarget** [comment]
@arv updated in author list as well.

**Comment by arv** [comment]
LGTM

**Comment by SrinivasanTarget** [comment]
@arv @johnjbarton Can you merge ?

**Pull request closed without merging**
