### PR TITLE
Pass options to PureES6Transformer

### LINKED ISSUE #1774: PureES6Transformer does not pass options to transformers
This breaks TypeAssertionTransformer, which wants to make use of options if `this.assertionAdded_` is true.

### PR DESCRIPTION
**Pull request by arv**
Fixes #1774

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton @caitp PTAL

**Comment by caitp** [comment]
The tests all still pass for me without the change in src/codegeneration/PureES6Transformer.js reverted, but the fix itself looks "probably" good.

**Comment by arv** [comment]
I had a `if (!options) throw 'xxx';` in there for a while to track down all bad callers. I could keep the assert or I can tweak the test... let me just fix the test.

**Comment by arv** [comment]
PTAL

**Comment by caitp** [comment]
looks good here

**Comment by johnjbarton** [comment]
LGTM, thanks.

**Pull request merged**
